NUMPY

In [ ]:
import numpy as np
import pandas as pd

In [17]:
np_array = np.array([1,2,3,4])
np_array*2

array([2, 4, 6, 8])

In [21]:
print(np_array.ndim)
print(np_array.shape)
print(np.sum(np_array))

1
(4,)
10


In [20]:
matrix = np.array([
    [1, 5, 6, 7],
    [2, 4, 2, 2]
])
np_array+matrix

array([[ 2,  7,  9, 11],
       [ 3,  6,  5,  6]])

In [24]:
lista = np.arange(0,100)
lista.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

PANDAS

In [63]:
#prv nacin
data = {
    "index": [1235, 43534, 43253, 54353],
    "name": ["Milena", "Jovana", "Ana", "Dimitar"],
    "grade": [5, 6, 7, 8]
}
df = pd.DataFrame(data)
df

index     name  grade
0   1235   Milena      5
1  43534   Jovana      6
2  43253      Ana      7
3  54353  Dimitar      8

In [64]:
#vtor nacin
df2 = pd.DataFrame(matrix,columns=[1,2,3,4])
df2

1  2  3  4
0  1  5  6  7
1  2  4  2  2

In [78]:
df.to_csv('stuff.csv')


RAZGLEDAJ ZA GROUPBY