<h1>NUMPY</h1>


In [2]:
import numpy as np
import pandas as pd

In [3]:
np_array = np.array([1,2,3,4])
np_array*2

array([2, 4, 6, 8])

In [4]:
print(np_array.ndim)
print(np_array.shape)
print(np.sum(np_array))

1
(4,)
10


In [5]:
matrix = np.array([
    [1, 5, 6, 7],
    [2, 4, 2, 2]
])
np_array+matrix

array([[ 2,  7,  9, 11],
       [ 3,  6,  5,  6]])

In [6]:
lista = np.arange(0,100)
lista.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

<h1>PANDAS</h1>
-   Pandas is an open-source data analysis and manipulation library for Python. It provides data structures like Series (1D) and DataFrame (2D), making it easy to work with structured data. It offers tools for reading/writing data, handling missing values, filtering, aggregation, and more, making it essential for data analysis, cleaning, and transformation.
<h3>Realationship between pandas and numpy</h3>
-   Pandas and NumPy are closely related, with pandas built on top of NumPy. Here’s how they interact:

	1.	Foundational Base:
	•	NumPy is the foundational library for numerical computing in Python, providing support for arrays and matrices.
	•	Pandas uses NumPy arrays internally to manage data within its Series and DataFrame objects.
	2.	Data Structures:
	•	NumPy provides basic structures like ndarray, designed for numerical operations.
	•	Pandas adds additional functionality for labeled data with the Series (1D) and DataFrame (2D), which are essentially enhanced versions of NumPy arrays that include row/column labels, handling missing data, and more.
	3.	Interoperability:
	•	Pandas can seamlessly convert its Series and DataFrames to NumPy arrays using .values or .to_numpy() methods.
	•	Many pandas functions use NumPy functions internally to perform operations efficiently.
	4.	Data Handling vs. Computation:
	•	NumPy is more efficient for numerical computation on raw data.
	•	Pandas is more focused on data handling, manipulation, and analysis, making it more user-friendly for data wrangling tasks.

In [7]:
broevi = [1235, 43534, 43253, 54353]
iminja = ["Milena", "Jovana", "Ana", "Dimitar"]
oceni = [5, 6, 7, 8]
l1 = []
for i,j,k in zip(broevi,iminja,oceni):
    l1.append({"index:":i,"name":j,"grade":k})

df = pd.DataFrame(l1)
df

index:     name  grade
0    1235   Milena      5
1   43534   Jovana      6
2   43253      Ana      7
3   54353  Dimitar      8

In [8]:
#vtor nacin
data = {
    "index": [1235, 43534, 43253, 54353],
    "name": ["Milena", "Jovana", "Ana", "Dimitar"],
    "grade": [5, 6, 7, 8]
}
df = pd.DataFrame(data)
df

index     name  grade
0   1235   Milena      5
1  43534   Jovana      6
2  43253      Ana      7
3  54353  Dimitar      8

In [9]:
#vtor nacin
df2 = pd.DataFrame(matrix,columns=[1,2,3,4])
df2

1  2  3  4
0  1  5  6  7
1  2  4  2  2

In [10]:
df.to_csv('stuff.csv')


<p>Internally, a DataFrame is more like a dictionary of Series objects:

	•	You can think of a DataFrame as a collection of Series objects, where each Series represents a column.
	•	Each Series in the DataFrame has its own index, but these indices are shared across all Series objects, which keeps the rows aligned.</p>

In [11]:
df

index     name  grade
0   1235   Milena      5
1  43534   Jovana      6
2  43253      Ana      7
3  54353  Dimitar      8